# Generated by Django 5.1.2 on 2024-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('16-30', '16 to 30'), ('7-15', '7 to 15'), ('2-6', '2 to 6'), ('30-50', '30 to 50')], max_length=10, null=True),
        ),
    ]
