# Generated by Django 5.1.2 on 2024-12-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_end_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('MV', 'Mountain View'), ('CC', 'City Center'), ('SV', 'Sea View')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('2-6', '2 to 6'), ('16-30', '16 to 30'), ('7-15', '7 to 15'), ('30-50', '30 to 50')], max_length=10, null=True),
        ),
    ]
