# Generated by Django 5.0.1 on 2024-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_location_image_alter_location_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('CC', 'City Center'), ('SV', 'Sea View'), ('MV', 'Mountain View')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('30-50', '30 to 50'), ('2-6', '2 to 6'), ('16-30', '16 to 30'), ('7-15', '7 to 15')], max_length=10, null=True),
        ),
    ]
