# Generated by Django 5.0.1 on 2024-12-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_location_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='booking',
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('SV', 'Sea View'), ('CC', 'City Center'), ('MV', 'Mountain View')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('7-15', '7 to 15'), ('30-50', '30 to 50'), ('2-6', '2 to 6'), ('16-30', '16 to 30')], max_length=10, null=True),
        ),
    ]
