# Generated by Django 5.0.1 on 2024-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_service_booking_service_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('MV', 'Mountain View'), ('CC', 'City Center'), ('SV', 'Sea View')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('7-15', '7 to 15'), ('16-30', '16 to 30'), ('2-6', '2 to 6'), ('30-50', '30 to 50')], max_length=10, null=True),
        ),
    ]
